[package]
name = "serial-log-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
chrono = "0.4.19"
once_cell = "1.13.0"
clap = { version = "3.2.12", features = ["derive"] }
serialport = "4.2.0"
